version: "3.9"
services:
  selenium-hub:
    image: selenium/hub:4.0.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - selenium-grid

  chrome1:
    image: selenium/node-chrome:4.0.0
    container_name: chrome1
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    depends_on:
      - selenium-hub
    ports:
      - "5901:5900" # VNC Port for chrome1
    networks:
      - selenium-grid

  chrome2:
    image: selenium/node-chrome:4.0.0
    container_name: chrome2
    shm_size: 2gb
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    depends_on:
      - selenium-hub
    ports:
      - "5902:5900" # VNC Port for chrome2
    networks:
      - selenium-grid

networks:
  selenium-grid:
    driver: bridge
